title = "Gitleaks - API de Pedidos"

[extend]
useDefault = true

[[rules]]
id = "generic-api-key"

[rules.allowlist]
description = "Ignorar falso positivo da URL interna do Prometheus no README"
condition = "AND"
regexTarget = "line"

regexes = [
    '''http://api-de-pedidos:8080/actuator/prometheus'''
]

paths = [
    '''^README\.md$'''
]