# Properties para desenvolvimento, utilizando banco H2

# Spring Datasource
spring.datasource.url=jdbc:h2:mem:api_pedidos_dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
api.security.token.chave-secreta=${JWT_SECRET}
api.security.token.expiracao=${JWT_EXPIRATION:900000}
api.security.token.expiracao-refresh=${JWT_REFRESH_EXPIRATION:604800000}
api.security.token.tempo-antes-expiracao-para-renovar=${JWT_RENEW_BEFORE_EXPIRATION:300000}

# WEBHOOK
api.webhook.fake.secret=${FAKE_WEBHOOK_SECRET}

# OpenAPI / Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true