# Properties para execucao local, utilizando banco PostgreSQL

# Docker Compose Local
spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose.yml
spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.readiness.timeout=2m

# Spring Datasource
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Console H2
spring.h2.console.enabled=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
api.security.token.chave-secreta=${JWT_SECRET}
api.security.token.expiracao=${JWT_EXPIRATION}
api.security.token.expiracao-refresh=${JWT_REFRESH_EXPIRATION}
api.security.token.tempo-antes-expiracao-para-renovar=${JWT_RENEW_BEFORE_EXPIRATION}

# WEBHOOK
api.webhook.fake.secret=${FAKE_WEBHOOK_SECRET}
