spring.application.name=api-de-pedidos

# Banco H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security
api.security.token.secret=${JWT_SECRET:minha-chave-muito-longa-e-segura-de-pelo-menos-32-caracteres}
api.security.token.refresh-secret=${JWT_SECRET:minha-chave-muito-longa-e-segura-de-refrsh-de-pelo-menos-32-caracteres}