spring.application.name=api-de-pedidos

# Banco H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Security
api.security.token.chave-secreta=${JWT_SECRET:minha-chave-muito-longa-e-segura-de-pelo-menos-32-caracteres}
api.security.token.expiracao=3600000
api.security.token.expiracao-refresh=604800000
api.security.token.tempo-antes-expiracao-para-renovar=300000