CREATE TABLE usuario
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(255),
    email             VARCHAR(255),
    senha             VARCHAR(255),
    data_criacao      DATE,
    senha_alterada_em BIGINT,
    ativo             BOOLEAN NOT NULL,
    cliente_vip       BOOLEAN NOT NULL,
    perfil            VARCHAR(30),

    CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE produto
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    preco     DECIMAL(19, 2),
    estoque   INTEGER,
    ativo     BOOLEAN NOT NULL,
    versao    BIGINT
);

CREATE TABLE cupom
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            VARCHAR(255)   NOT NULL,
    percentual        DECIMAL(19, 2) NOT NULL,
    data_inicio       TIMESTAMP,
    data_fim          TIMESTAMP,
    ativo             BOOLEAN        NOT NULL,
    limite_uso        INTEGER,
    quantidade_de_uso INTEGER,
    versao            BIGINT,

    CONSTRAINT uk_cupom_codigo UNIQUE (codigo)
);

CREATE TABLE pedido
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT,
    data_criacao   TIMESTAMP,
    valor_bruto    DECIMAL(19, 2),
    valor_desconto DECIMAL(19, 2),
    valor_final    DECIMAL(19, 2),
    status         VARCHAR(50) NOT NULL,
    cupom_id       BIGINT,
    versao         BIGINT,

    CONSTRAINT fk_pedido_usuario
        FOREIGN KEY (usuario_id)
            REFERENCES usuario (id),

    CONSTRAINT fk_pedido_cupom
        FOREIGN KEY (cupom_id)
            REFERENCES cupom (id)
);

CREATE TABLE item_pedido
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT,
    produto_id     BIGINT,
    preco_unitario DECIMAL(19, 2),
    quantidade     INTEGER,

    CONSTRAINT fk_item_pedido_pedido
        FOREIGN KEY (pedido_id)
            REFERENCES pedido (id),

    CONSTRAINT fk_item_pedido_produto
        FOREIGN KEY (produto_id)
            REFERENCES produto (id)
);

CREATE TABLE refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(500) NOT NULL,
    expiration TIMESTAMP,
    revogado   BOOLEAN      NOT NULL,
    usuario_id BIGINT,

    CONSTRAINT uk_refresh_token_token UNIQUE (token),

    CONSTRAINT fk_refresh_token_usuario
        FOREIGN KEY (usuario_id)
            REFERENCES usuario (id)
);

CREATE TABLE blacklisted_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(2000),
    expiration TIMESTAMP
);

CREATE TABLE idempotency_key
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave         VARCHAR(255) NOT NULL,
    endpoint      VARCHAR(255) NOT NULL,
    usuario_id    VARCHAR(255) NOT NULL,
    metodo_http   VARCHAR(20)  NOT NULL,
    request_hash  VARCHAR(255) NOT NULL,
    resposta_json CLOB,
    criada_em     TIMESTAMP    NOT NULL,
    expira_em     TIMESTAMP    NOT NULL,

    CONSTRAINT uk_idempotency_key
        UNIQUE (chave, endpoint, metodo_http, usuario_id)
);

CREATE INDEX idx_pedido_usuario
    ON pedido (usuario_id);

CREATE INDEX idx_item_pedido_pedido
    ON item_pedido (pedido_id);

CREATE INDEX idx_item_pedido_produto
    ON item_pedido (produto_id);

CREATE INDEX idx_refresh_token_usuario
    ON refresh_token (usuario_id);

CREATE INDEX idx_blacklisted_token_expiration
    ON blacklisted_token (expiration);

CREATE INDEX idx_idempotency_key_expira_em
    ON idempotency_key (expira_em);