CREATE TABLE historico_pedido
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id    BIGINT       NOT NULL,
    status       VARCHAR(255) NOT NULL,
    descricao    VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP    NOT NULL,

    CONSTRAINT fk_historico_pedido_pedido
        FOREIGN KEY (pedido_id)
            REFERENCES pedido (id)
);

CREATE TABLE notificacao
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT        NOT NULL,
    pedido_id    BIGINT        NOT NULL,
    titulo       VARCHAR(255)  NOT NULL,
    mensagem     VARCHAR(1000) NOT NULL,
    tipo         VARCHAR(255)  NOT NULL,
    lida         BOOLEAN       NOT NULL,
    data_criacao TIMESTAMP     NOT NULL,

    CONSTRAINT fk_notificacao_usuario
        FOREIGN KEY (usuario_id)
            REFERENCES usuario (id),

    CONSTRAINT fk_notificacao_pedido
        FOREIGN KEY (pedido_id)
            REFERENCES pedido (id)
);

CREATE TABLE auditoria
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT        NOT NULL,
    pedido_id    BIGINT        NOT NULL,
    recurso      VARCHAR(80)   NOT NULL,
    tipo_acao    VARCHAR(255)  NOT NULL,
    descricao    VARCHAR(1000) NOT NULL,
    data_criacao TIMESTAMP     NOT NULL,

    CONSTRAINT fk_auditoria_usuario
        FOREIGN KEY (usuario_id)
            REFERENCES usuario (id),

    CONSTRAINT fk_auditoria_pedido
        FOREIGN KEY (pedido_id)
            REFERENCES pedido (id)
);

CREATE INDEX idx_historico_pedido_pedido
    ON historico_pedido (pedido_id);

CREATE INDEX idx_notificacao_usuario
    ON notificacao (usuario_id);

CREATE INDEX idx_notificacao_pedido
    ON notificacao (pedido_id);

CREATE INDEX idx_notificacao_usuario_lida
    ON notificacao (usuario_id, lida);

CREATE INDEX idx_auditoria_usuario
    ON auditoria (usuario_id);

CREATE INDEX idx_auditoria_pedido
    ON auditoria (pedido_id);

CREATE INDEX idx_auditoria_recurso_pedido
    ON auditoria (recurso, pedido_id);