CREATE TABLE pagamento
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id         BIGINT         NOT NULL,
    valor             DECIMAL(19, 2) NOT NULL,
    forma_pagamento   VARCHAR(30)    NOT NULL,
    status_pagamento  VARCHAR(30)    NOT NULL,
    codigo_transacao  VARCHAR(100),
    mensagem_retorno  VARCHAR(1000),
    data_criacao      TIMESTAMP      NOT NULL,
    data_atualizacao  TIMESTAMP      NOT NULL,

    CONSTRAINT fk_pagamento_pedido
        FOREIGN KEY (pedido_id)
            REFERENCES pedido (id)
);

CREATE INDEX idx_pagamento_pedido
    ON pagamento (pedido_id);

CREATE INDEX idx_pagamento_status
    ON pagamento (status_pagamento);