CREATE TABLE webhook_pagamento_recebido
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          VARCHAR(150) NOT NULL,
    codigo_transacao  VARCHAR(150) NOT NULL,
    status_recebido   VARCHAR(30)  NOT NULL,
    payload           TEXT         NOT NULL,
    data_recebimento  TIMESTAMP    NOT NULL,

    CONSTRAINT uk_webhook_pagamento_event_id
        UNIQUE (event_id)
);

CREATE INDEX idx_webhook_pagamento_codigo_transacao
    ON webhook_pagamento_recebido (codigo_transacao);

CREATE INDEX idx_webhook_pagamento_data_recebimento
    ON webhook_pagamento_recebido (data_recebimento);