CREATE TABLE transacao_gateway_fake
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_transacao  VARCHAR(100) NOT NULL,
    status_pagamento  VARCHAR(30)  NOT NULL,
    data_criacao      TIMESTAMP    NOT NULL,
    data_atualizacao  TIMESTAMP    NOT NULL,

    CONSTRAINT uk_transacao_gateway_fake_codigo
        UNIQUE (codigo_transacao)
);

CREATE INDEX idx_transacao_gateway_fake_status
    ON transacao_gateway_fake (status_pagamento);

CREATE INDEX idx_transacao_gateway_fake_data_atualizacao
    ON transacao_gateway_fake (data_atualizacao);